export { CCQ_METIERS, CCQ_SECTEURS, CCQ_TAUX_2025_2026, getTauxHoraire, calculerCoutMain } from './ccqServiceEnhanced';
export type { CCQMetier, CCQSecteur, CCQTauxHoraire } from './ccqServiceEnhanced';
export { analyzePageWithAI, elementsToTakeoffItems, createTakeoffLayer, CSC_CATEGORIES, DEFAULT_LAYERS, exportTakeoffToExcel } from './aiTakeoffService';
export type { DetectedElement, AIDetectedItem, AIAnalysisResult, TakeoffItem, TakeoffLayer, PageInfo, AnalysisOptions } from './aiTakeoffService';
export { generateSoumissionPDF, downloadSoumissionPDF, openSoumissionPDF } from './pdfSoumissionService';
export type { SoumissionPDFData } from './pdfSoumissionService';
export { excelService, EXCEL_TEMPLATES } from './excelServiceAdvanced';
export type { ExcelTemplate, ExcelImportResult } from './excelServiceAdvanced';
export { verifyRBQLicense } from './rbqService';
export { appelsOffresCanadaService } from './appelsOffresCanadaService';
export type { AppelOffre, RechercheParams } from './appelsOffresCanadaService';
export { emailService } from './emailService';
export { generateFacturePDF, pdfFactureService } from './pdfFactureService';
export type { FacturePDFData } from './pdfFactureService';
export { calculateQuebecTaxes, QUEBEC_TAX_RATES } from '@/types/pricing-types';
